import { jsPDF } from 'jspdf';

/**
 * Exports a message content to a branded PDF
 * @param {Object} message - The message object { role, content, createdAt }
 */
export const exportToPDF = (message) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    // 1. Add Branding Header
    doc.setFillColor(42, 42, 42); // #2a2a2a
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('IntelliChat', margin, 25);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(180, 180, 180);
    doc.text('AI Generated Response', margin, 32);

    // 2. Add Meta Information
    const date = new Date(message.createdAt || Date.now()).toLocaleString();
    doc.setTextColor(110, 110, 110);
    doc.setFontSize(9);
    doc.text(`Date: ${date}`, pageWidth - margin, 25, { align: 'right' });

    // 3. Add Content
    doc.setTextColor(33, 33, 33);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    // Handle text wrapping
    const splitText = doc.splitTextToSize(message.content, contentWidth);
    let cursorY = 55;

    // Handle pagination
    splitText.forEach((line) => {
        if (cursorY > 280) {
            doc.addPage();
            cursorY = 20;
        }
        doc.text(line, margin, cursorY);
        cursorY += 7;
    });

    // 4. Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Page ${i} of ${pageCount} - Generated by IntelliChat`,
            pageWidth / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: 'center' }
        );
    }

    // 5. Save the file
    const filename = `IntelliChat_Response_${new Date().getTime()}.pdf`;
    doc.save(filename);
};
